name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.email "joguel63@gmail.com"
          git config --global user.name "joguel63"

      - name: Configure remote URL with token
        run: git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/joguel63/hmi-banda-transportadora

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 